import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Mail, Phone } from 'lucide-react';
import { SEOHead } from "@/components/SEOHead";

const Terms = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <SEOHead title={"Terms of Service | Nyzora"} description={"Terms governing use of Nyzora's marketplace, design tools, and creator/maker programs."} />
      <Header />
      <main className="flex-1 container py-12">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-2">Terms & Conditions</h1>
          <p className="text-muted-foreground mb-8">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>

          <Card className="mb-8">
            <CardHeader>
              <CardTitle>Contact Support</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-muted-foreground">
                For any questions or support regarding these Terms & Conditions, please contact:
              </p>
              <div className="border rounded-lg p-4">
                  <div className="space-y-2 text-sm">
                    <div className="flex items-center gap-2">
                      <Phone className="h-4 w-4 text-muted-foreground" />
                      <a href="tel:+18885002881" className="hover:underline">1 (888) 500-2881</a>
                    </div>
                    <div className="flex items-center gap-2">
                      <Mail className="h-4 w-4 text-muted-foreground" />
                      <a href="mailto:contact@nyzora.ai" className="hover:underline">
                        contact@nyzora.ai
                      </a>
                    </div>
                  </div>
                </div>
            </CardContent>
          </Card>

          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
              <p className="text-muted-foreground mb-4">
                By creating an account, browsing products, generating designs, or making purchases on Nyzora
                ("Nyzora", "we", "us"), you acknowledge that you have read, understood, and agree to be bound by
                these Terms &amp; Conditions and our Privacy Policy.
              </p>
              <p className="text-muted-foreground">
                Nyzora operates two fulfilment tracks, and some terms below differ between them:
                <strong> Nyzora Originals</strong> — personalised keepsake pieces made to order and shipped from our
                US production partner — and the <strong>Nyzora marketplace</strong>, where creator-designed pieces are
                manufactured to order by verified makers.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">2. User Content & Ownership</h2>
              <p className="text-muted-foreground mb-4">
                By uploading or submitting any design, image, or file ("Content") to our platform, you represent and warrant that:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4">
                <li>You are the sole owner of the Content, or</li>
                <li>You have obtained all necessary rights, licenses, or permissions to use and share the Content</li>
              </ul>
              <p className="text-muted-foreground mb-4">
                You retain ownership of your Content, but by submitting it to Nyzora, you grant us a non-exclusive,
                royalty-free, worldwide license to display, reproduce, and manufacture products derived from the
                Content on our platform.
              </p>
              <p className="text-muted-foreground">
                Photographs you upload to personalise an order (for example a pet photo) are used only to generate
                your preview and manufacture your piece, and are handled as described in our Privacy Policy. Designs
                and 3D models generated by our AI tools for your own personal order are yours to own and use.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">3. Creator Terms</h2>
              
              <h3 className="text-xl font-semibold mb-3">3.1 Creator Application</h3>
              <p className="text-muted-foreground mb-4">
                To become a Creator on our platform, you must submit an application with accurate information.
                We reserve the right to approve or reject applications at our discretion.
              </p>

              <h3 className="text-xl font-semibold mb-3">3.2 Product Submission</h3>
              <p className="text-muted-foreground mb-4">
                Every listing is reviewed by Nyzora before it goes live, and any later edit returns the listing to
                review. Creators must ensure that:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4">
                <li>All submitted designs are original or properly licensed</li>
                <li>Products meet our quality and sustainability standards</li>
                <li>Product descriptions and specifications are accurate</li>
                <li>Images are high-quality and represent the actual product</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3">3.3 Intellectual Property</h3>
              <p className="text-muted-foreground mb-4">
                You agree not to upload Content that infringes upon the intellectual property rights of others.
                Nyzora does not pre-screen every user upload. If you believe your IP has been infringed,
                please contact us and we will review and take appropriate action.
              </p>

              <h3 className="text-xl font-semibold mb-3">3.4 Pricing and Earnings</h3>
              <p className="text-muted-foreground mb-4">
                Creators set their own selling prices above the Manufacturing Base Price (MBP) calculated by our platform. Creators currently keep 100% of the markup (the difference between their selling price and MBP) on every sale. The MBP covers manufacturing, fulfilment and Nyzora's maker commission, and is calculated by our platform; its internal composition is confidential. Nyzora reserves the right to introduce a platform fee on each transaction in the future; any such change will be announced transparently and with reasonable notice before taking effect.
              </p>

              <h3 className="text-xl font-semibold mb-3">3.5 Payments</h3>
              <p className="text-muted-foreground mb-4">
                Creator earnings are calculated after each completed sale and become payable once the order has
                shipped and any replacement window has passed. You must provide valid bank details for payment
                processing. Minimum payout thresholds apply as specified in your dashboard. Pieces listed under the
                Nyzora Originals house profile are produced by Nyzora and are excluded from creator payouts.
              </p>

              <h3 className="text-xl font-semibold mb-3">3.7 AI Credits</h3>
              <p className="text-muted-foreground mb-4">
                Design generation consumes AI credits allocated to your account. Credits have no cash value, are
                non-transferable and non-refundable, and may be adjusted where we detect abuse or automated misuse.
              </p>

              <h3 className="text-xl font-semibold mb-3">3.6 Product Quality and Listing Management</h3>
              <p className="text-muted-foreground">
                Creator acknowledges that Nyzora has authority to pause listings if product issues cause excessive 
                support requests or returns. This measure ensures quality standards are maintained across the platform 
                and protects both customers and the platform's reputation.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">4. Customer Terms</h2>
              
              <h3 className="text-xl font-semibold mb-3">4.1 Orders and Payment</h3>
              <p className="text-muted-foreground mb-4">
                By placing an order, you agree to pay the price shown at checkout plus any applicable taxes and
                shipping fees. Prices for Nyzora Originals are quoted in US dollars. All payments are processed
                securely through our payment partners; we never store your card details. Depending on your card and
                region, your bank may settle the transaction in your local currency at the rate shown at checkout,
                and may apply its own conversion or international transaction fees.
              </p>

              <h3 className="text-xl font-semibold mb-3">4.2 Shipping and Delivery</h3>
              <p className="text-muted-foreground mb-4">
                Delivery times are estimates and may vary. Nyzora Originals are typically produced in 2-3 days and
                delivered within 7-8 days in the United States. Larger marketplace furniture is manufactured to order
                and typically requires 21-35 days for production and delivery, with custom pieces occasionally taking
                longer. Tracking is added to your order in your account as soon as the piece ships.
              </p>

              <h3 className="text-xl font-semibold mb-3">4.3 Personalisation and Previews</h3>
              <p className="text-muted-foreground mb-4">
                Personalised pieces are produced from the preview render you approve, using the heading, footnote and
                any photograph you supply, within the character limits shown on the product page. Please check your
                spelling, dates and photograph before ordering. Renders are a close representation of the finished
                piece; minor variations in surface texture, tone and layer detail are inherent to the process and are
                not defects.
              </p>

              <h3 className="text-xl font-semibold mb-3">4.4 Returns, Refunds and Cancellations</h3>
              <p className="text-muted-foreground mb-4">
                Every piece is made to order for a single customer and enters production shortly after payment.
                It therefore cannot be resold or restocked, and the following terms apply:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 mb-4">
                <li>
                  <strong>Free replacement</strong> is provided where the item arrives damaged or defective (for
                  example cracked, warped, or incorrectly engraved by us). Contact us with photographs within 30 days
                  of delivery and we remake and reship at our cost. Where a replacement is not possible, we will
                  refund you.
                </li>
                <li>
                  <strong>Free replacement</strong> is provided where the delivered item does not materially match the
                  approved preview render. We remake and reship at our cost; no return postage is payable by you.
                </li>
                <li>
                  <strong>No cancellations</strong> once an order has been placed and production has begun.
                </li>
                <li>
                  <strong>No change-of-mind returns or exchanges</strong>, and no refunds for personalization errors
                  (including spelling, dates, or uploaded photographs) supplied by you. Please review your preview and
                  your text carefully before ordering.
                </li>
              </ul>
              <p className="text-muted-foreground">
                Renders are a close representation of the final piece; minor variations in surface texture, tone and
                layer detail are inherent to the process and are not defects.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">5. User Accounts</h2>
              <p className="text-muted-foreground mb-4">
                You are responsible for:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorized use</li>
                <li>Providing accurate and current information</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">6. Prohibited Activities</h2>
              <p className="text-muted-foreground mb-4">
                You agree not to:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Use the platform for any illegal purpose</li>
                <li>Submit false, misleading, or fraudulent information</li>
                <li>Infringe on intellectual property rights</li>
                <li>Attempt to manipulate pricing or reviews</li>
                <li>Interfere with the platform's operation or security</li>
                <li>Scrape or collect data without permission</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">7. Responsibility & Liability</h2>
              <p className="text-muted-foreground mb-4">
                You acknowledge and agree that you are solely responsible for any Content you upload.
              </p>
              <p className="text-muted-foreground">
                Nyzora will not be held liable for any claims, damages, or disputes arising from Content
                uploaded by users. To the maximum extent permitted by law, we shall not be liable for any indirect,
                incidental, special, or consequential damages arising from your use of the platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">8. Indemnification</h2>
              <p className="text-muted-foreground mb-4">
                You agree to indemnify, defend, and hold harmless Nyzora, its affiliates, employees,
                and partners from any claim, liability, damage, cost, or expense (including legal fees) arising from:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Your uploaded Content</li>
                <li>Any violation of these Terms</li>
                <li>Your use of the platform</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">9. Content Removal & Enforcement</h2>
              <p className="text-muted-foreground mb-4">Nyzora reserves the right to:</p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2">
                <li>Remove or disable access to any Content suspected of infringing IP rights</li>
                <li>Suspend or terminate accounts involved in repeated violations</li>
                <li>Comply with applicable legal obligations</li>
                <li>Modify, suspend, or discontinue any aspect of our platform</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">10. Dispute Resolution</h2>
              <p className="text-muted-foreground">
                Any disputes arising from these terms shall be resolved through good faith negotiation. If resolution
                cannot be reached, these terms are governed by the laws of India and disputes shall be subject to the
                courts of Mumbai, Maharashtra.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">11. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We may update these Terms & Conditions from time to time. We will notify you of significant changes 
                by posting a notice on the platform or sending an email. Continued use after changes constitutes 
                acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">12. Contact Information</h2>
              <p className="text-muted-foreground mb-4">
                For questions, concerns, or support regarding these Terms & Conditions:
              </p>
              <div className="bg-muted/50 rounded-lg p-6 space-y-3">
                <div>
                  <p className="text-sm text-muted-foreground">Email: contact@nyzora.ai</p>
                  <p className="text-sm text-muted-foreground">Phone: 1 (888) 500-2881</p>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
