// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-products.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search catalog products",
  description: "Search Nyzora's published catalog of creator-designed furniture and objects by keyword and/or category.",
  inputSchema: {
    query: z.string().trim().max(200).optional().describe("Keyword to match against product name."),
    category: z.string().trim().max(80).optional().describe("Category filter, e.g. Chair, Lighting, Objects."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("designer_products").select("id, name, slug, category, description, designer_price, image_url, manufacturing_method, production_region, total_sales").eq("status", "approved").order("total_sales", { ascending: false }).limit(limit ?? 20);
    if (query) q = q.ilike("name", `%${query}%`);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details for a single published Nyzora product by its slug or id.",
  inputSchema: {
    slug: z2.string().trim().min(1).max(200).describe("Product slug (preferred) or product UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const supabase = supabaseForUser(ctx);
    const columns = "id, name, slug, category, description, materials_description, designer_price, dimensions, weight, image_url, model_url, lead_time_days, manufacturing_method, production_region, total_sales, created_at";
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(slug);
    const { data, error } = await supabase.from("designer_products").select(columns).eq("status", "approved").eq(isUuid ? "id" : "slug", slug).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No published product found for "${slug}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-my-designs.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_designs_default = defineTool3({
  name: "list_my_designs",
  title: "List my designs",
  description: "List the signed-in creator's own submitted designs with their review status (pending, approved, rejected).",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected"]).optional().describe("Filter by review status."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await supabase.from("designer_profiles").select("id, name, status").eq("user_id", ctx.getUserId()).maybeSingle();
    if (profileError) throw new ToolError3(profileError.message);
    if (!profile) {
      return {
        content: [{ type: "text", text: "You don't have a creator profile on Nyzora yet." }],
        structuredContent: { designs: [] }
      };
    }
    let q = supabase.from("designer_products").select("id, name, slug, category, status, rejection_reason, designer_price, base_price, image_url, total_sales, created_at").eq("designer_id", profile.id).order("created_at", { ascending: false }).limit(input.limit ?? 50);
    if (input.status) q = q.eq("status", input.status);
    const { data, error } = await q;
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { creator: profile.name, designs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-credits.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_credits_default = defineTool4({
  name: "get_my_credits",
  title: "Get my AI credit balance",
  description: "Return the signed-in user's remaining Nyzora AI design credits and recent credit activity.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: credits, error } = await supabase.from("user_credits").select("balance, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) throw new ToolError4(error.message);
    const { data: transactions } = await supabase.from("credit_transactions").select("amount, type, description, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(10);
    const balance = credits?.balance ?? 0;
    return {
      content: [{ type: "text", text: `Credit balance: ${balance}` }],
      structuredContent: { balance, updated_at: credits?.updated_at ?? null, recent: transactions ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rdcfakdhgndnhgzfkuvw";
var mcp_default = defineMcp({
  name: "nyzora",
  title: "Nyzora",
  version: "0.1.0",
  instructions: "Tools for Nyzora, an AI design-to-manufacturing marketplace. Use `search_products` and `get_product` to explore the published catalog, `list_my_designs` to check the signed-in creator's submissions and review status, and `get_my_credits` for their remaining AI design credits.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_designs_default, get_my_credits_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
