// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-products.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search catalog products",
  description: "Search Nyzora's published catalog of creator-designed furniture and objects by keyword and/or category.",
  inputSchema: {
    query: z.string().trim().max(200).optional().describe("Keyword to match against product name."),
    category: z.string().trim().max(80).optional().describe("Category filter, e.g. Chair, Lighting, Objects."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("designer_products").select("id, name, slug, category, description, designer_price, image_url, manufacturing_method, production_region, total_sales").eq("status", "approved").order("total_sales", { ascending: false }).limit(limit ?? 20);
    if (query) q = q.ilike("name", `%${query}%`);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details for a single published Nyzora product by its slug or id.",
  inputSchema: {
    slug: z2.string().trim().min(1).max(200).describe("Product slug (preferred) or product UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const supabase = supabaseForUser(ctx);
    const columns = "id, name, slug, category, description, materials_description, designer_price, dimensions, weight, image_url, model_url, lead_time_days, manufacturing_method, production_region, total_sales, created_at";
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(slug);
    const { data, error } = await supabase.from("designer_products").select(columns).eq("status", "approved").eq(isUuid ? "id" : "slug", slug).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No published product found for "${slug}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-my-designs.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_designs_default = defineTool3({
  name: "list_my_designs",
  title: "List my designs",
  description: "List the signed-in creator's own submitted designs with their review status (pending, approved, rejected).",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected"]).optional().describe("Filter by review status."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await supabase.from("designer_profiles").select("id, name, status").eq("user_id", ctx.getUserId()).maybeSingle();
    if (profileError) throw new ToolError3(profileError.message);
    if (!profile) {
      return {
        content: [{ type: "text", text: "You don't have a creator profile on Nyzora yet." }],
        structuredContent: { designs: [] }
      };
    }
    let q = supabase.from("designer_products").select("id, name, slug, category, status, rejection_reason, designer_price, base_price, image_url, total_sales, created_at").eq("designer_id", profile.id).order("created_at", { ascending: false }).limit(input.limit ?? 50);
    if (input.status) q = q.eq("status", input.status);
    const { data, error } = await q;
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { creator: profile.name, designs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-credits.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_credits_default = defineTool4({
  name: "get_my_credits",
  title: "Get my AI credit balance",
  description: "Return the signed-in user's remaining Nyzora AI design credits and recent credit activity.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: credits, error } = await supabase.from("user_credits").select("balance, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) throw new ToolError4(error.message);
    const { data: transactions } = await supabase.from("credit_transactions").select("amount, type, description, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(10);
    const balance = credits?.balance ?? 0;
    return {
      content: [{ type: "text", text: `Credit balance: ${balance}` }],
      structuredContent: { balance, updated_at: credits?.updated_at ?? null, recent: transactions ?? [] }
    };
  }
});

// src/lib/mcp/tools/meta-me.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/meta-token.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
var FB_API = "https://graph.facebook.com/v18.0";
var REFRESH_BUFFER_MS = 24 * 60 * 60 * 1e3;
function runtimeEnv2(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv2(names) {
  for (const name of names) {
    const value = runtimeEnv2(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl2() {
  const url = configuredEnv2(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey2() {
  const direct = configuredEnv2(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv2("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv2(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function appCreds() {
  const appId = runtimeEnv2("META_APP_ID");
  const appSecret = runtimeEnv2("META_APP_SECRET");
  const currentEnvToken = runtimeEnv2("META_ACCESS_TOKEN");
  if (!appId || !appSecret) {
    throw new Error("META_APP_ID and META_APP_SECRET must be configured for Meta/Instagram posting");
  }
  if (!currentEnvToken) {
    throw new Error("META_ACCESS_TOKEN not configured");
  }
  return { appId, appSecret, currentEnvToken };
}
async function fetchJson(url) {
  const res = await fetch(url);
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`Meta token exchange failed (${res.status}): ${text.slice(0, 500)}`);
  }
  try {
    return text ? JSON.parse(text) : {};
  } catch {
    return { raw: text };
  }
}
async function exchangeForLongLived(shortToken, appId, appSecret) {
  const url = `${FB_API}/oauth/access_token?grant_type=fb_exchange_token&client_id=${appId}&client_secret=${appSecret}&fb_exchange_token=${shortToken}`;
  const data = await fetchJson(url);
  if (data.error?.message) {
    throw new Error(`Meta token exchange error: ${data.error.message}`);
  }
  if (!data.access_token) {
    throw new Error("Meta token exchange did not return an access_token");
  }
  const expiresInMs = (data.expires_in ?? 5184e3) * 1e3;
  return {
    access_token: data.access_token,
    token_type: data.token_type ?? "bearer",
    expires_at: new Date(Date.now() + expiresInMs).toISOString()
  };
}
function supabaseForUser2(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient2(supabaseProjectUrl2(), supabasePublishableKey2(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function loadStoredState(ctx) {
  const userId = ctx.getUserId();
  if (!userId) throw new Error("Not authenticated");
  const supabase = supabaseForUser2(ctx);
  const { data, error } = await supabase.from("user_connector_tokens").select("meta_defaults").eq("user_id", userId).maybeSingle();
  if (error) throw new Error(`Failed to load Meta token state: ${error.message}`);
  const meta_defaults = data?.meta_defaults ?? {};
  const tokenState = meta_defaults?.meta_token ? meta_defaults.meta_token : null;
  return { meta_defaults, tokenState };
}
async function saveTokenState(ctx, meta_defaults, tokenState) {
  const userId = ctx.getUserId();
  if (!userId) throw new Error("Not authenticated");
  const supabase = supabaseForUser2(ctx);
  const next = { ...meta_defaults ?? {}, meta_token: tokenState };
  const { error } = await supabase.from("user_connector_tokens").upsert({ user_id: userId, meta_defaults: next }, { onConflict: "user_id" });
  if (error) throw new Error(`Failed to save Meta token state: ${error.message}`);
}
function isExpiringSoon(tokenState) {
  if (!tokenState?.access_token) return true;
  if (!tokenState.expires_at) return false;
  const expiresAt = new Date(tokenState.expires_at).getTime();
  return Date.now() + REFRESH_BUFFER_MS >= expiresAt;
}
async function getMetaAccessToken(ctx) {
  const { appId, appSecret, currentEnvToken } = appCreds();
  const { meta_defaults, tokenState } = await loadStoredState(ctx);
  if (!isExpiringSoon(tokenState)) {
    return tokenState.access_token;
  }
  const sourceToken = tokenState?.access_token ?? currentEnvToken;
  const fresh = await exchangeForLongLived(sourceToken, appId, appSecret);
  await saveTokenState(ctx, meta_defaults, fresh);
  return fresh.access_token;
}
async function getMetaDefaults(ctx) {
  const { meta_defaults } = await loadStoredState(ctx);
  const stored = meta_defaults ?? {};
  if (!stored.ig_user_id) {
    return {
      ...stored,
      ig_user_id: "17841436891682401",
      ig_username: "nyzora.ai",
      page_id: "1087872784403919"
    };
  }
  return stored;
}

// src/lib/mcp/tools/meta-me.ts
var FB_API2 = "https://graph.facebook.com/v18.0";
async function fb(path, token, init = {}) {
  const res = await fetch(`${FB_API2}${path}`, {
    ...init,
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init.headers ?? {} }
  });
  const text = await res.text();
  if (!res.ok) {
    throw new ToolError5(`Meta ${res.status} ${path}: ${text.slice(0, 500)}`);
  }
  try {
    return text ? JSON.parse(text) : {};
  } catch {
    return { raw: text };
  }
}
var meta_me_default = defineTool5({
  name: "meta_me",
  title: "Meta account info",
  description: "Returns the connected Meta user id/name and the Facebook pages they manage, including linked Instagram Business accounts. Use this to discover page IDs and Instagram account IDs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError5("Not authenticated");
    }
    const token = await getMetaAccessToken(ctx);
    const me = await fb(
      "/me?fields=id,name,accounts{name,id,access_token,instagram_business_account{id,username}}",
      token
    );
    return {
      content: [{ type: "text", text: JSON.stringify(me, null, 2) }],
      structuredContent: {
        user_id: me.id,
        name: me.name,
        pages: me.accounts?.data ?? []
      }
    };
  }
});

// src/lib/mcp/tools/meta-ig-post.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var FB_API3 = "https://graph.facebook.com/v18.0";
async function fb2(path, token, init = {}) {
  const res = await fetch(`${FB_API3}${path}`, {
    ...init,
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init.headers ?? {} }
  });
  const text = await res.text();
  if (!res.ok) {
    throw new ToolError6(`Meta ${res.status} ${path}: ${text.slice(0, 500)}`);
  }
  try {
    return text ? JSON.parse(text) : {};
  } catch {
    return { raw: text };
  }
}
var meta_ig_post_default = defineTool6({
  name: "meta_ig_post",
  title: "Post to Instagram",
  description: "Publish a single-image Instagram feed post. Uses the default Instagram account configured in user_connector_tokens unless ig_user_id is provided. The image_url must be publicly reachable by Meta's servers.",
  inputSchema: {
    image_url: z4.string().url().describe("Publicly reachable image URL"),
    caption: z4.string().min(1).describe("Caption text"),
    ig_user_id: z4.string().optional().describe("Instagram Business account id (optional; uses default if omitted)")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ image_url, caption, ig_user_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError6("Not authenticated");
    }
    const token = await getMetaAccessToken(ctx);
    const defaults = await getMetaDefaults(ctx);
    const resolvedIgUserId = ig_user_id ?? defaults.ig_user_id ?? "";
    if (!resolvedIgUserId) {
      throw new ToolError6(
        "No Instagram Business account ID configured. Run meta_me to find your account ID, then store it in user_connector_tokens meta_defaults.ig_user_id."
      );
    }
    const encodedImageUrl = encodeURIComponent(image_url);
    const encodedCaption = encodeURIComponent(caption);
    const container = await fb2(
      `/${resolvedIgUserId}/media?image_url=${encodedImageUrl}&caption=${encodedCaption}`,
      token,
      { method: "POST" }
    );
    if (!container.id) {
      throw new ToolError6("Instagram media container creation failed");
    }
    let status = "IN_PROGRESS";
    let lastError = "";
    for (let attempt = 0; attempt < 20; attempt++) {
      await new Promise((r) => setTimeout(r, attempt === 0 ? 2e3 : 3e3));
      const s = await fb2(`/${container.id}?fields=status_code,status`, token);
      status = s.status_code ?? "IN_PROGRESS";
      lastError = s.status ?? "";
      if (status === "FINISHED") break;
      if (status === "ERROR" || status === "EXPIRED") {
        throw new ToolError6(`Instagram media processing failed (${status}): ${lastError}`);
      }
    }
    if (status !== "FINISHED") {
      throw new ToolError6(`Instagram media was still processing after ~60s (status: ${status}). ${lastError}`);
    }
    const published = await fb2(
      `/${resolvedIgUserId}/media_publish?creation_id=${container.id}`,
      token,
      { method: "POST" }
    );
    return {
      content: [{ type: "text", text: `Posted to Instagram. Media ID: ${published.id ?? "unknown"}` }],
      structuredContent: { container_id: container.id, media_id: published.id }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rdcfakdhgndnhgzfkuvw";
var mcp_default = defineMcp({
  name: "nyzora",
  title: "Nyzora",
  version: "0.2.0",
  instructions: "Tools for Nyzora, an AI design-to-manufacturing marketplace. Use `search_products` and `get_product` to explore the published catalog, `list_my_designs` to check the signed-in creator's submissions and review status, and `get_my_credits` for their remaining AI design credits. Use `meta_me` to inspect the connected Meta/Instagram account, and `meta_ig_post` to publish an image post to Instagram.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_designs_default, get_my_credits_default, meta_me_default, meta_ig_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
