// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-products.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search catalog products",
  description: "Search Nyzora's published catalog of creator-designed furniture and objects by keyword and/or category.",
  inputSchema: {
    query: z.string().trim().max(200).optional().describe("Keyword to match against product name."),
    category: z.string().trim().max(80).optional().describe("Category filter, e.g. Chair, Lighting, Objects."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("designer_products").select("id, name, slug, category, description, designer_price, image_url, manufacturing_method, production_region, total_sales").eq("status", "approved").order("total_sales", { ascending: false }).limit(limit ?? 20);
    if (query) q = q.ilike("name", `%${query}%`);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details for a single published Nyzora product by its slug or id.",
  inputSchema: {
    slug: z2.string().trim().min(1).max(200).describe("Product slug (preferred) or product UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const supabase = supabaseForUser(ctx);
    const columns = "id, name, slug, category, description, materials_description, designer_price, dimensions, weight, image_url, model_url, lead_time_days, manufacturing_method, production_region, total_sales, created_at";
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(slug);
    const { data, error } = await supabase.from("designer_products").select(columns).eq("status", "approved").eq(isUuid ? "id" : "slug", slug).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No published product found for "${slug}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-my-designs.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_designs_default = defineTool3({
  name: "list_my_designs",
  title: "List my designs",
  description: "List the signed-in creator's own submitted designs with their review status (pending, approved, rejected).",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected"]).optional().describe("Filter by review status."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await supabase.from("designer_profiles").select("id, name, status").eq("user_id", ctx.getUserId()).maybeSingle();
    if (profileError) throw new ToolError3(profileError.message);
    if (!profile) {
      return {
        content: [{ type: "text", text: "You don't have a creator profile on Nyzora yet." }],
        structuredContent: { designs: [] }
      };
    }
    let q = supabase.from("designer_products").select("id, name, slug, category, status, rejection_reason, designer_price, base_price, image_url, total_sales, created_at").eq("designer_id", profile.id).order("created_at", { ascending: false }).limit(input.limit ?? 50);
    if (input.status) q = q.eq("status", input.status);
    const { data, error } = await q;
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { creator: profile.name, designs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-credits.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_credits_default = defineTool4({
  name: "get_my_credits",
  title: "Get my AI credit balance",
  description: "Return the signed-in user's remaining Nyzora AI design credits and recent credit activity.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: credits, error } = await supabase.from("user_credits").select("balance, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) throw new ToolError4(error.message);
    const { data: transactions } = await supabase.from("credit_transactions").select("amount, type, description, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(10);
    const balance = credits?.balance ?? 0;
    return {
      content: [{ type: "text", text: `Credit balance: ${balance}` }],
      structuredContent: { balance, updated_at: credits?.updated_at ?? null, recent: transactions ?? [] }
    };
  }
});

// src/lib/mcp/tools/meta-me.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/meta-token.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
var FB_API = "https://graph.facebook.com/v18.0";
var REFRESH_BUFFER_MS = 24 * 60 * 60 * 1e3;
function runtimeEnv2(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv2(names) {
  for (const name of names) {
    const value = runtimeEnv2(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl2() {
  const url = configuredEnv2(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey2() {
  const direct = configuredEnv2(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv2("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv2(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function appCreds() {
  const appId = runtimeEnv2("META_APP_ID");
  const appSecret = runtimeEnv2("META_APP_SECRET");
  const currentEnvToken = runtimeEnv2("META_ACCESS_TOKEN");
  if (!appId || !appSecret) {
    throw new Error("META_APP_ID and META_APP_SECRET must be configured for Meta/Instagram posting");
  }
  if (!currentEnvToken) {
    throw new Error("META_ACCESS_TOKEN not configured");
  }
  return { appId, appSecret, currentEnvToken };
}
async function fetchJson(url) {
  const res = await fetch(url);
  const text2 = await res.text();
  if (!res.ok) {
    throw new Error(`Meta token exchange failed (${res.status}): ${text2.slice(0, 500)}`);
  }
  try {
    return text2 ? JSON.parse(text2) : {};
  } catch {
    return { raw: text2 };
  }
}
async function exchangeForLongLived(shortToken, appId, appSecret) {
  const url = `${FB_API}/oauth/access_token?grant_type=fb_exchange_token&client_id=${appId}&client_secret=${appSecret}&fb_exchange_token=${shortToken}`;
  const data = await fetchJson(url);
  if (data.error?.message) {
    throw new Error(`Meta token exchange error: ${data.error.message}`);
  }
  if (!data.access_token) {
    throw new Error("Meta token exchange did not return an access_token");
  }
  const expiresInMs = (data.expires_in ?? 5184e3) * 1e3;
  return {
    access_token: data.access_token,
    token_type: data.token_type ?? "bearer",
    expires_at: new Date(Date.now() + expiresInMs).toISOString()
  };
}
function supabaseForUser2(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient2(supabaseProjectUrl2(), supabasePublishableKey2(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function loadStoredState(ctx) {
  const userId = ctx.getUserId();
  if (!userId) throw new Error("Not authenticated");
  const supabase = supabaseForUser2(ctx);
  const { data, error } = await supabase.from("user_connector_tokens").select("meta_defaults").eq("user_id", userId).maybeSingle();
  if (error) throw new Error(`Failed to load Meta token state: ${error.message}`);
  const meta_defaults = data?.meta_defaults ?? {};
  const tokenState = meta_defaults?.meta_token ? meta_defaults.meta_token : null;
  return { meta_defaults, tokenState };
}
async function saveTokenState(ctx, meta_defaults, tokenState) {
  const userId = ctx.getUserId();
  if (!userId) throw new Error("Not authenticated");
  const supabase = supabaseForUser2(ctx);
  const next = { ...meta_defaults ?? {}, meta_token: tokenState };
  const { error } = await supabase.from("user_connector_tokens").upsert({ user_id: userId, meta_defaults: next }, { onConflict: "user_id" });
  if (error) throw new Error(`Failed to save Meta token state: ${error.message}`);
}
function isExpiringSoon(tokenState) {
  if (!tokenState?.access_token) return true;
  if (!tokenState.expires_at) return false;
  const expiresAt = new Date(tokenState.expires_at).getTime();
  return Date.now() + REFRESH_BUFFER_MS >= expiresAt;
}
async function getMetaAccessToken(ctx) {
  const { appId, appSecret, currentEnvToken } = appCreds();
  const { meta_defaults, tokenState } = await loadStoredState(ctx);
  if (!isExpiringSoon(tokenState)) {
    return tokenState.access_token;
  }
  const sourceToken = tokenState?.access_token ?? currentEnvToken;
  const fresh = await exchangeForLongLived(sourceToken, appId, appSecret);
  await saveTokenState(ctx, meta_defaults, fresh);
  return fresh.access_token;
}
async function getMetaPageToken(ctx, pageId) {
  const { meta_defaults } = await loadStoredState(ctx);
  const defaults = meta_defaults ?? {};
  const resolvedPageId = pageId ?? defaults.page_id ?? "1087872784403919";
  const cache = defaults.meta_page_tokens ?? {};
  const cached = cache[resolvedPageId];
  if (cached) {
    const probe = await fetch(
      `${FB_API}/${resolvedPageId}?fields=id&access_token=${encodeURIComponent(cached)}`
    );
    if (probe.ok) return cached;
  }
  const userToken = await getMetaAccessToken(ctx);
  const res = await fetch(
    `${FB_API}/${resolvedPageId}?fields=access_token&access_token=${encodeURIComponent(userToken)}`
  );
  const data = await res.json();
  if (!res.ok || !data.access_token) {
    throw new Error(`Failed to fetch Meta page token: ${data.error?.message ?? res.status}`);
  }
  const userId = ctx.getUserId();
  if (userId) {
    const supabase = supabaseForUser2(ctx);
    const { meta_defaults: latest } = await loadStoredState(ctx);
    const latestDefaults = latest ?? {};
    const nextCache = {
      ...latestDefaults.meta_page_tokens ?? {},
      [resolvedPageId]: data.access_token
    };
    await supabase.from("user_connector_tokens").upsert(
      { user_id: userId, meta_defaults: { ...latestDefaults, meta_page_tokens: nextCache } },
      { onConflict: "user_id" }
    );
  }
  return data.access_token;
}
async function getMetaDefaults(ctx) {
  const { meta_defaults } = await loadStoredState(ctx);
  const stored = meta_defaults ?? {};
  if (!stored.ig_user_id) {
    return {
      ...stored,
      ig_user_id: "17841436891682401",
      ig_username: "nyzora.ai",
      page_id: "1087872784403919"
    };
  }
  return stored;
}

// src/lib/mcp/tools/meta-me.ts
var FB_API2 = "https://graph.facebook.com/v18.0";
async function fb(path, token, init = {}) {
  const res = await fetch(`${FB_API2}${path}`, {
    ...init,
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init.headers ?? {} }
  });
  const text2 = await res.text();
  if (!res.ok) {
    throw new ToolError5(`Meta ${res.status} ${path}: ${text2.slice(0, 500)}`);
  }
  try {
    return text2 ? JSON.parse(text2) : {};
  } catch {
    return { raw: text2 };
  }
}
var meta_me_default = defineTool5({
  name: "meta_me",
  title: "Meta account info",
  description: "Returns the connected Meta user id/name and the Facebook pages they manage, including linked Instagram Business accounts. Use this to discover page IDs and Instagram account IDs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError5("Not authenticated");
    }
    const token = await getMetaAccessToken(ctx);
    const me = await fb(
      "/me?fields=id,name,accounts{name,id,access_token,instagram_business_account{id,username}}",
      token
    );
    return {
      content: [{ type: "text", text: JSON.stringify(me, null, 2) }],
      structuredContent: {
        user_id: me.id,
        name: me.name,
        pages: me.accounts?.data ?? []
      }
    };
  }
});

// src/lib/mcp/tools/meta-ig-post.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var FB_API3 = "https://graph.facebook.com/v18.0";
async function fb2(path, token, init = {}) {
  const res = await fetch(`${FB_API3}${path}`, {
    ...init,
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init.headers ?? {} }
  });
  const text2 = await res.text();
  if (!res.ok) {
    throw new ToolError6(`Meta ${res.status} ${path}: ${text2.slice(0, 500)}`);
  }
  try {
    return text2 ? JSON.parse(text2) : {};
  } catch {
    return { raw: text2 };
  }
}
var meta_ig_post_default = defineTool6({
  name: "meta_ig_post",
  title: "Post to Instagram",
  description: "Publish a single-image Instagram feed post. Uses the default Instagram account configured in user_connector_tokens unless ig_user_id is provided. The image_url must be publicly reachable by Meta's servers.",
  inputSchema: {
    image_url: z4.string().url().describe("Publicly reachable image URL"),
    caption: z4.string().min(1).describe("Caption text"),
    ig_user_id: z4.string().optional().describe("Instagram Business account id (optional; uses default if omitted)")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ image_url, caption, ig_user_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      throw new ToolError6("Not authenticated");
    }
    const defaults = await getMetaDefaults(ctx);
    const token = await getMetaPageToken(ctx, defaults.page_id);
    const resolvedIgUserId = ig_user_id ?? defaults.ig_user_id ?? "";
    if (!resolvedIgUserId) {
      throw new ToolError6(
        "No Instagram Business account ID configured. Run meta_me to find your account ID, then store it in user_connector_tokens meta_defaults.ig_user_id."
      );
    }
    const encodedImageUrl = encodeURIComponent(image_url);
    const encodedCaption = encodeURIComponent(caption);
    const container = await fb2(
      `/${resolvedIgUserId}/media?image_url=${encodedImageUrl}&caption=${encodedCaption}`,
      token,
      { method: "POST" }
    );
    if (!container.id) {
      throw new ToolError6("Instagram media container creation failed");
    }
    let status = "IN_PROGRESS";
    let lastError = "";
    for (let attempt = 0; attempt < 20; attempt++) {
      await new Promise((r) => setTimeout(r, attempt === 0 ? 2e3 : 3e3));
      const s = await fb2(`/${container.id}?fields=status_code,status`, token);
      status = s.status_code ?? "IN_PROGRESS";
      lastError = s.status ?? "";
      if (status === "FINISHED") break;
      if (status === "ERROR" || status === "EXPIRED") {
        throw new ToolError6(`Instagram media processing failed (${status}): ${lastError}`);
      }
    }
    if (status !== "FINISHED") {
      throw new ToolError6(`Instagram media was still processing after ~60s (status: ${status}). ${lastError}`);
    }
    const published = await fb2(
      `/${resolvedIgUserId}/media_publish?creation_id=${container.id}`,
      token,
      { method: "POST" }
    );
    return {
      content: [{ type: "text", text: `Posted to Instagram. Media ID: ${published.id ?? "unknown"}` }],
      structuredContent: { container_id: container.id, media_id: published.id }
    };
  }
});

// src/lib/mcp/tools/meta-ads-accounts.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";

// src/lib/mcp/tools/meta-ads-api.ts
import { ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@0.26.1";
var ADS_API = "https://graph.facebook.com/v21.0";
var MAX_DAILY_BUDGET_USD = 200;
async function graph(path, token, init = {}) {
  const { form, ...rest } = init;
  const res = await fetch(`${ADS_API}${path}`, {
    ...rest,
    method: form ? "POST" : rest.method ?? "GET",
    headers: {
      Authorization: `Bearer ${token}`,
      ...form ? { "Content-Type": "application/x-www-form-urlencoded" } : {},
      ...rest.headers ?? {}
    },
    body: form ? new URLSearchParams(form).toString() : rest.body
  });
  const text2 = await res.text();
  if (!res.ok) throw new ToolError7(`Meta Ads ${res.status} ${path}: ${text2.slice(0, 700)}`);
  try {
    return text2 ? JSON.parse(text2) : {};
  } catch {
    return { raw: text2 };
  }
}
async function adsToken(ctx) {
  if (!ctx.isAuthenticated()) throw new ToolError7("Not authenticated");
  return getMetaAccessToken(ctx);
}
function normalizeActId(id) {
  const trimmed = id.trim();
  return trimmed.startsWith("act_") ? trimmed : `act_${trimmed}`;
}
function assertBudget(usd) {
  if (!Number.isFinite(usd) || usd <= 0) throw new ToolError7("Daily budget must be a positive number of USD.");
  if (usd > MAX_DAILY_BUDGET_USD) {
    throw new ToolError7(
      `Daily budget $${usd} exceeds the built-in safety cap of $${MAX_DAILY_BUDGET_USD}/day. Ask the owner to raise MAX_DAILY_BUDGET_USD in code.`
    );
  }
}
function text(obj) {
  return { content: [{ type: "text", text: JSON.stringify(obj, null, 2) }] };
}
async function uploadAdVideo(act, token, fileUrl, name) {
  const uploaded = await graph(`/${act}/advideos`, token, {
    form: { file_url: fileUrl, name }
  });
  if (!uploaded?.id) throw new ToolError7("Meta did not return a video id for the uploaded creative.");
  return uploaded.id;
}
async function waitForVideoReady(videoId, token, { timeoutMs = 18e4, intervalMs = 5e3 } = {}) {
  const deadline = Date.now() + timeoutMs;
  let last = "unknown";
  while (Date.now() < deadline) {
    const info = await graph(`/${videoId}?fields=status`, token);
    last = info?.status?.video_status ?? "unknown";
    if (last === "ready") return;
    if (last === "error") throw new ToolError7("Meta failed to process the uploaded video.");
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  throw new ToolError7(`Video ${videoId} was still "${last}" after waiting. Retry once processing finishes.`);
}
async function getVideoThumbnail(videoId, token) {
  const res = await graph(
    `/${videoId}/thumbnails`,
    token
  );
  const list = res?.data ?? [];
  return (list.find((t) => t.is_preferred) ?? list[0])?.uri;
}

// src/lib/mcp/tools/meta-ads-accounts.ts
var meta_ads_accounts_default = defineTool7({
  name: "meta_ads_accounts",
  title: "Meta ad accounts & structure",
  description: "Lists the Meta ad accounts the connected Nyzora account can manage, including currency, spend cap, amount spent and account status. Optionally drills into one account to list its campaigns, ad sets and ads with their status and budgets. Read-only.",
  inputSchema: {
    ad_account_id: z5.string().optional().describe("Optional ad account id (with or without the act_ prefix) to list campaigns/ad sets/ads for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ ad_account_id }, ctx) => {
    const token = await adsToken(ctx);
    if (!ad_account_id) {
      const data = await graph(
        "/me/adaccounts?fields=id,account_id,name,currency,account_status,amount_spent,spend_cap,balance,funding_source_details&limit=50",
        token
      );
      return { ...text(data), structuredContent: { accounts: data.data ?? [] } };
    }
    const act = normalizeActId(ad_account_id);
    const [campaigns, adsets, ads] = await Promise.all([
      graph(
        `/${act}/campaigns?fields=id,name,status,effective_status,objective,daily_budget,lifetime_budget,created_time&limit=50`,
        token
      ),
      graph(
        `/${act}/adsets?fields=id,name,status,effective_status,campaign_id,daily_budget,optimization_goal,targeting&limit=50`,
        token
      ),
      graph(
        `/${act}/ads?fields=id,name,status,effective_status,adset_id,creative{id,thumbnail_url}&limit=50`,
        token
      )
    ]);
    const payload = { ad_account_id: act, campaigns: campaigns.data ?? [], adsets: adsets.data ?? [], ads: ads.data ?? [] };
    return { ...text(payload), structuredContent: payload };
  }
});

// src/lib/mcp/tools/meta-ads-insights.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var meta_ads_insights_default = defineTool8({
  name: "meta_ads_insights",
  title: "Meta ads performance",
  description: "Reads Meta Ads performance (spend, impressions, reach, clicks, CTR, CPC, CPM, purchases, purchase value and ROAS) for an ad account, campaign, ad set or ad over a date preset. Read-only \u2014 never changes anything.",
  inputSchema: {
    object_id: z6.string().describe("Ad account id (act_... or numeric), campaign id, ad set id or ad id."),
    level: z6.enum(["account", "campaign", "adset", "ad"]).default("campaign").describe("Breakdown level."),
    date_preset: z6.enum(["today", "yesterday", "last_7d", "last_14d", "last_30d", "this_month", "last_month", "maximum"]).default("last_7d")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ object_id, level, date_preset }, ctx) => {
    const token = await adsToken(ctx);
    const target = level === "account" ? normalizeActId(object_id) : object_id.trim();
    const fields = "campaign_name,adset_name,ad_name,spend,impressions,reach,frequency,clicks,ctr,cpc,cpm,actions,action_values,purchase_roas";
    const data = await graph(
      `/${target}/insights?level=${level}&date_preset=${date_preset}&fields=${fields}&limit=100`,
      token
    );
    const payload = { object_id: target, level, date_preset, rows: data.data ?? [] };
    return { ...text(payload), structuredContent: payload };
  }
});

// src/lib/mcp/tools/meta-ads-manage.ts
import { defineTool as defineTool9, ToolError as ToolError8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^4.4.3";
var meta_ads_manage_default = defineTool9({
  name: "meta_ads_manage",
  title: "Pause, resume or rebudget a Meta ad",
  description: "Changes the status (ACTIVE/PAUSED) or daily budget of an existing Meta campaign, ad set or ad. Turning something ACTIVE starts spending money, so it requires confirm to be set to the exact string 'I APPROVE SPEND'. Pausing never requires confirmation. Daily budgets are capped by a built-in safety limit.",
  inputSchema: {
    object_id: z7.string().describe("Campaign, ad set or ad id to modify."),
    status: z7.enum(["ACTIVE", "PAUSED"]).optional().describe("New status. ACTIVE requires confirm."),
    daily_budget_usd: z7.number().positive().optional().describe("New daily budget in USD (campaign or ad set only). Requires confirm."),
    confirm: z7.string().optional().describe("Must be exactly 'I APPROVE SPEND' for any change that can start or increase spending.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ object_id, status, daily_budget_usd, confirm }, ctx) => {
    const token = await adsToken(ctx);
    const spendy = status === "ACTIVE" || typeof daily_budget_usd === "number";
    if (spendy && confirm !== "I APPROVE SPEND") {
      throw new ToolError8(
        "This change can start or increase ad spend. Ask the account owner to approve, then re-run with confirm: 'I APPROVE SPEND'."
      );
    }
    if (!status && daily_budget_usd === void 0) throw new ToolError8("Nothing to change: pass status and/or daily_budget_usd.");
    const form = {};
    if (status) form.status = status;
    if (daily_budget_usd !== void 0) {
      assertBudget(daily_budget_usd);
      form.daily_budget = String(Math.round(daily_budget_usd * 100));
    }
    const result = await graph(`/${object_id}`, token, { form });
    const payload = { object_id, applied: form, result };
    return { ...text(payload), structuredContent: payload };
  }
});

// src/lib/mcp/tools/meta-ads-create.ts
import { defineTool as defineTool10, ToolError as ToolError9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^4.4.3";
var meta_ads_create_default = defineTool10({
  name: "meta_ads_create_campaign",
  title: "Draft a Meta ads campaign (paused)",
  description: "Creates a complete Meta ads stack \u2014 campaign, ad set with targeting and daily budget, image OR video creative and ad \u2014 for a Nyzora product. Pass image_url for a static ad or video_url for a video ad (the video is uploaded to the ad account and transcoded first). Everything is created in PAUSED state and cannot spend money. Use meta_ads_manage with confirm to launch it after the owner approves.",
  inputSchema: {
    ad_account_id: z8.string().describe("Ad account id (act_... or numeric)."),
    page_id: z8.string().describe("Facebook Page id that the ad runs from."),
    name: z8.string().min(3).max(120).describe("Campaign name, e.g. 'Originals \u2014 Pet Bust \u2014 US Prospecting'."),
    objective: z8.enum(["OUTCOME_SALES", "OUTCOME_TRAFFIC", "OUTCOME_AWARENESS", "OUTCOME_ENGAGEMENT"]).default("OUTCOME_SALES"),
    daily_budget_usd: z8.number().positive().describe("Daily budget in USD for the ad set."),
    image_url: z8.string().url().optional().describe("Publicly reachable image URL for a static ad creative. Provide either image_url or video_url."),
    video_url: z8.string().url().optional().describe(
      "Publicly reachable MP4 URL for a video ad creative. The video is uploaded to the ad account and Meta transcodes it before the creative is built."
    ),
    video_thumbnail_url: z8.string().url().optional().describe("Optional custom thumbnail for the video ad. Defaults to Meta's preferred auto-generated frame."),
    primary_text: z8.string().min(1).max(500).describe("Main ad body copy."),
    headline: z8.string().min(1).max(60).describe("Ad headline."),
    link_url: z8.string().url().describe("Landing page URL on nyzora.ai."),
    call_to_action: z8.enum(["SHOP_NOW", "LEARN_MORE", "ORDER_NOW", "SIGN_UP"]).default("SHOP_NOW"),
    countries: z8.array(z8.string().length(2)).default(["US"]).describe("ISO country codes to target."),
    age_min: z8.number().int().min(18).max(65).default(25),
    age_max: z8.number().int().min(18).max(65).default(55),
    pixel_id: z8.string().optional().describe(
      "Meta pixel id. Required for OUTCOME_SALES so the ad set optimizes for a conversion event instead of clicks."
    ),
    optimize_for: z8.enum(["PURCHASE", "INITIATED_CHECKOUT", "CONTENT_VIEW", "LEAD"]).default("PURCHASE").describe("Pixel event the sales ad set optimizes for. Use INITIATED_CHECKOUT while purchase volume is thin."),
    interest_ids: z8.array(z8.string()).default([]).describe("Meta detailed-targeting interest ids (look them up with meta_ads_audiences search_interests)."),
    locales: z8.array(z8.number().int()).default([]).describe("Meta locale ids, e.g. 6 = English (US), 24 = English (UK). Empty means all languages."),
    custom_audience_ids: z8.array(z8.string()).default([]).describe("Custom audience ids to target \u2014 used for the retargeting ad set."),
    excluded_custom_audience_ids: z8.array(z8.string()).default([]).describe("Custom audience ids to exclude, e.g. past purchasers.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    const token = await adsToken(ctx);
    assertBudget(input.daily_budget_usd);
    if (input.age_max < input.age_min) throw new ToolError9("age_max must be greater than or equal to age_min.");
    if (!input.image_url && !input.video_url) {
      throw new ToolError9("Provide either image_url (static ad) or video_url (video ad).");
    }
    if (input.image_url && input.video_url) {
      throw new ToolError9("Provide only one of image_url or video_url, not both.");
    }
    const act = normalizeActId(input.ad_account_id);
    const campaign = await graph(`/${act}/campaigns`, token, {
      form: {
        name: input.name,
        objective: input.objective,
        status: "PAUSED",
        special_ad_categories: "[]",
        is_adset_budget_sharing_enabled: "false"
      }
    });
    const isSales = input.objective === "OUTCOME_SALES";
    if (isSales && !input.pixel_id) {
      throw new ToolError9(
        "pixel_id is required for OUTCOME_SALES \u2014 without it Meta optimizes for clicks, not buyers."
      );
    }
    const optimization_goal = isSales ? "OFFSITE_CONVERSIONS" : input.objective === "OUTCOME_AWARENESS" ? "REACH" : "LINK_CLICKS";
    const targeting = {
      geo_locations: { countries: input.countries },
      age_min: input.age_min,
      age_max: input.age_max,
      targeting_automation: { advantage_audience: 0 }
    };
    if (input.interest_ids.length) {
      targeting.flexible_spec = [{ interests: input.interest_ids.map((id) => ({ id })) }];
    }
    if (input.locales.length) targeting.locales = input.locales;
    if (input.custom_audience_ids.length) {
      targeting.custom_audiences = input.custom_audience_ids.map((id) => ({ id }));
    }
    if (input.excluded_custom_audience_ids.length) {
      targeting.excluded_custom_audiences = input.excluded_custom_audience_ids.map((id) => ({ id }));
    }
    const adsetForm = {
      name: `${input.name} \u2014 Ad set`,
      campaign_id: campaign.id,
      daily_budget: String(Math.round(input.daily_budget_usd * 100)),
      billing_event: "IMPRESSIONS",
      optimization_goal,
      bid_strategy: "LOWEST_COST_WITHOUT_CAP",
      targeting: JSON.stringify(targeting),
      status: "PAUSED"
    };
    if (isSales && input.pixel_id) {
      adsetForm.promoted_object = JSON.stringify({
        pixel_id: input.pixel_id,
        custom_event_type: input.optimize_for
      });
    }
    const adset = await graph(`/${act}/adsets`, token, { form: adsetForm });
    let videoId;
    let objectStorySpec;
    if (input.video_url) {
      videoId = await uploadAdVideo(act, token, input.video_url, `${input.name} \u2014 Video`);
      await waitForVideoReady(videoId, token);
      const thumbnail = input.video_thumbnail_url ?? await getVideoThumbnail(videoId, token);
      if (!thumbnail) {
        throw new ToolError9("No thumbnail available for the uploaded video. Pass video_thumbnail_url explicitly.");
      }
      objectStorySpec = {
        page_id: input.page_id,
        video_data: {
          video_id: videoId,
          image_url: thumbnail,
          message: input.primary_text,
          title: input.headline,
          call_to_action: { type: input.call_to_action, value: { link: input.link_url } }
        }
      };
    } else {
      objectStorySpec = {
        page_id: input.page_id,
        link_data: {
          link: input.link_url,
          message: input.primary_text,
          name: input.headline,
          picture: input.image_url,
          call_to_action: { type: input.call_to_action, value: { link: input.link_url } }
        }
      };
    }
    const creative = await graph(`/${act}/adcreatives`, token, {
      form: {
        name: `${input.name} \u2014 Creative`,
        object_story_spec: JSON.stringify(objectStorySpec),
        degrees_of_freedom_spec: JSON.stringify({ creative_features_spec: { standard_enhancements: { enroll_status: "OPT_OUT" } } })
      }
    });
    const ad = await graph(`/${act}/ads`, token, {
      form: {
        name: `${input.name} \u2014 Ad`,
        adset_id: adset.id,
        creative: JSON.stringify({ creative_id: creative.id }),
        status: "PAUSED"
      }
    });
    const payload = {
      status: "PAUSED \u2014 nothing is spending yet",
      ad_account_id: act,
      campaign_id: campaign.id,
      adset_id: adset.id,
      creative_id: creative.id,
      creative_type: input.video_url ? "video" : "image",
      ...videoId ? { video_id: videoId } : {},
      ad_id: ad.id,
      daily_budget_usd: input.daily_budget_usd,
      launch_instructions: "Owner approval required. To go live, call meta_ads_manage with the campaign_id, ad set id and ad id set to ACTIVE and confirm: 'I APPROVE SPEND'."
    };
    return { ...text(payload), structuredContent: payload };
  }
});

// src/lib/mcp/tools/meta-ads-audiences.ts
import { defineTool as defineTool11, ToolError as ToolError10 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^4.4.3";
var EVENT_AUDIENCES = {
  customizers: {
    event: "CustomizeProduct",
    days: 30,
    label: "Customized a preview (30d)"
  },
  checkout_starters: {
    event: "InitiateCheckout",
    days: 30,
    label: "Started checkout (30d)"
  },
  viewers: {
    event: "ViewContent",
    days: 30,
    label: "Viewed a product (30d)"
  },
  purchasers: {
    event: "Purchase",
    days: 180,
    label: "Purchased (180d) \u2014 use as an exclusion"
  }
};
var meta_ads_audiences_default = defineTool11({
  name: "meta_ads_audiences",
  title: "List, create and look up Meta audiences",
  description: "Manages retargeting inputs. action 'list' returns existing custom audiences on the ad account. action 'create' builds a website custom audience from a Nyzora pixel event (customizers, checkout_starters, viewers, purchasers) \u2014 use 'customizers' for retargeting and 'purchasers' as an exclusion. action 'search_interests' looks up Meta detailed-targeting interest ids by keyword (e.g. 'pet loss', 'dog memorial') so ad sets target real ids. Creates no spend of any kind.",
  inputSchema: {
    action: z9.enum(["list", "create", "search_interests"]),
    ad_account_id: z9.string().optional().describe("Ad account id (act_... or numeric). Required for list and create."),
    pixel_id: z9.string().optional().describe("Meta pixel id. Required for action 'create'."),
    audience: z9.enum(["customizers", "checkout_starters", "viewers", "purchasers"]).optional().describe("Which pixel-event audience to create."),
    query: z9.string().min(2).max(80).optional().describe("Keyword for action 'search_interests'."),
    limit: z9.number().int().min(1).max(50).default(25)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    const token = await adsToken(ctx);
    if (input.action === "search_interests") {
      if (!input.query) throw new ToolError10("query is required for action 'search_interests'.");
      const res = await graph(
        `/search?type=adinterest&q=${encodeURIComponent(input.query)}&limit=${input.limit}`,
        token
      );
      const payload2 = {
        query: input.query,
        interests: (res.data ?? []).map((i) => ({
          id: i.id,
          name: i.name,
          audience_size: i.audience_size_lower_bound ?? i.audience_size,
          path: i.path
        }))
      };
      return { ...text(payload2), structuredContent: payload2 };
    }
    if (!input.ad_account_id) throw new ToolError10("ad_account_id is required for this action.");
    const act = normalizeActId(input.ad_account_id);
    if (input.action === "list") {
      const res = await graph(
        `/${act}/customaudiences?fields=id,name,subtype,approximate_count_lower_bound,delivery_status,operation_status&limit=${input.limit}`,
        token
      );
      const payload2 = { ad_account_id: act, audiences: res.data ?? [] };
      return { ...text(payload2), structuredContent: payload2 };
    }
    if (!input.audience) throw new ToolError10("audience is required for action 'create'.");
    if (!input.pixel_id) throw new ToolError10("pixel_id is required for action 'create'.");
    const spec = EVENT_AUDIENCES[input.audience];
    const rule = {
      inclusions: {
        operator: "or",
        rules: [
          {
            event_sources: [{ type: "pixel", id: input.pixel_id }],
            retention_seconds: spec.days * 86400,
            filter: {
              operator: "and",
              filters: [{ field: "event", operator: "eq", value: spec.event }]
            }
          }
        ]
      }
    };
    const created = await graph(`/${act}/customaudiences`, token, {
      form: {
        name: `Nyzora \u2014 ${spec.label}`,
        subtype: "WEBSITE",
        description: `Auto-built from pixel event ${spec.event} over ${spec.days} days.`,
        rule: JSON.stringify(rule),
        prefill: "1"
      }
    });
    const payload = {
      audience_id: created.id,
      name: `Nyzora \u2014 ${spec.label}`,
      pixel_event: spec.event,
      retention_days: spec.days,
      note: input.audience === "purchasers" ? "Pass this id as excluded_custom_audience_ids on prospecting and retargeting ad sets." : "Pass this id as custom_audience_ids on the retargeting ad set. It needs ~1,000 people before it can deliver."
    };
    return { ...text(payload), structuredContent: payload };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rdcfakdhgndnhgzfkuvw";
var mcp_default = defineMcp({
  name: "nyzora",
  title: "Nyzora",
  version: "0.5.0",
  instructions: "Tools for Nyzora, an AI design-to-manufacturing marketplace. Use `search_products` and `get_product` to explore the published catalog, `list_my_designs` to check the signed-in creator's submissions and review status, and `get_my_credits` for their remaining AI design credits. Use `meta_me` to inspect the connected Meta/Instagram account, and `meta_ig_post` to publish an image post to Instagram. For paid media use `meta_ads_accounts` (ad accounts, campaigns, ad sets, ads), `meta_ads_insights` (spend, CTR, CPM, ROAS), `meta_ads_create_campaign` (drafts a full campaign that is always created PAUSED) `meta_ads_audiences` (pixel-based retargeting audiences and interest lookup) and `meta_ads_manage` (pause/resume/rebudget). Anything that can start or increase ad spend requires the owner\u2019s explicit confirm string \u2014 never launch an ad without asking the owner first.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_designs_default, get_my_credits_default, meta_me_default, meta_ig_post_default, meta_ads_accounts_default, meta_ads_insights_default, meta_ads_create_default, meta_ads_audiences_default, meta_ads_manage_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
